---
sudo: required
dist: xenial   # required for Python >= 3.7  
language: python
python:
  - 3.6
  - 3.7
  - 3.8
addons:
  apt:
    packages:
    - curl
    - libxml2-utils
    - pandoc
    - aspell
    - aspell-en
before_install:
  - sudo apt-get update -qq
  - gem install mdl --no-ri --no-rdoc
install: 
  - python3 -m pip install tox  
script:
- rm -rf ./output
- rm -rf ./cache
- rm -rf ./plugins/*
- curl https://raw.githubusercontent.com/mike42/mdcheckr/master/mdcheckr -o mdcheckr
- chmod +x mdcheckr
- sudo cp mdcheckr /usr/local/bin
- /usr/local/bin/mdcheckr -v