---
sudo: required
dist: xenial   # required for Python >= 3.7  
language: python
python:
  - 3.6
  - 3.7
addons:
  apt:
    packages:
    - curl
    - libxml2-utils
    - pandoc
    - aspell
    - aspell-en
before_install:
  - sudo apt-get update -qq
  - gem install mdl --no-ri --no-rdoc
install: 
  - python3 -m pip install tox  
script:
- rm -rf ./output
- rm -rf ./cache
- rm -rf ./plugins/*
- curl https://raw.githubusercontent.com/mike42/mdcheckr/master/mdcheckr -o mdcheckr
- chmod +x mdcheckr
- sudo cp mdcheckr /usr/local/bin
- /usr/local/bin/mdcheckr -v
# show the PWD on remote
- echo "test dir `pwd`"
# run tox testing during CI, could also "make test"
#- cd python && tox
# test to validate the markdown files in this repo
#- mdl -c .mdlrc ./hacker_cookbook/templates
env:
  global:
  - secure: hIZQzfFOVm9MjxueEEYDfDETg6MpDJEfpinu+iAA0STVIqZaq85AIA8l7hc9AgqRrtz0PUPZAdLwYw0E8mYPaffXkPKRNAEUt4IlWJLMjOCJiZHo67oOWxop7p28dnD2c9dYqD4FKPnzJd40nM0yXWTcBsxqe7miBF+0em7Unh3JAF6z15yqWpTSA2M/noFuxN6IShkhp8EO4bt5j3dHBoqBEkizO6QeYIFLIoIkCdlFsujd5lMX3Ec1ydewkBIW7G1L8+IisBD0PhPv3LhqcyHpsTBgdTkxhdpCIeRw/6wll6z0QRcxkJDxrkTBfZWgZR5QkH09zj7UrPxckCpGwNtVJKXzbLvTZkWagpEH/fW1GW+I5E4UAS9AHvhbhViz1pJnKbmwLVfCvh4uO8odqjVhCTswLTHEx4k1aeLRvLPvscWBumatiGDtge+KKvBmAwdeH9nn7ej0mGmMh9vK6MVdLljBArc4HBkFtIxfT8Os1uWnFIbV8IBhSeVpMUwDoqRJsN0sKFiwaP0IKYcL7EuCaLZ/axCJ4AR6YAWKO2u8ynZsP4u/Y615dSXhRRDcAN1hJcSFURhM6K2qFo+nt43bwsH+A4zpMJF0gP0+0+LtGvtFB6e62+MAeWRb/McNSzXiktL422ATq5NVuU9Oi6zT1qbDgwCQDZo1YmeQQwc=
notifications:
  slack:
    secure: Bsdbc77V1ygNT3ngOXs2lXQ8NT1Lp/D8UXcaEKj9yV7q7g0sljJh9/6LvuUjWTYRqmHoGLDrsThgEQuayhqAeGIoH2KF871L2Rwm2RUg4FmX6x865YOL2UjxXIbmig3itgR4EByxSr6uWMCcBMHPkzP6tPmtPo0Sp/vw0Tn8UBXk7jHSAYHSN6jHR1l22Ask4kZVhhX6eLYQ26A1VafzycoaQIq/vt9sB+JXHd226d+SleAys4qg5X593yGNtAWFR7y9L9LCtOJZS4t1iB/LS8K20/k8giXEjBkMODJT8RVY69EGwLNvt8045HtRYcE/peLucgKFi0V5J9e7pq0YuM9gL7oJJ8LCX3Dy2ZUOOAYcmhK+jIYSl/LCgqU+/JkqVVuJ7G1AUAIiwQ/Xa0ryQjLSLedC153gmnkdc8mgOYoqxdzH8wS4dSgjOc3gkNprN4OqfuXAn5WUBBV5zpkdgome/l7dItbniEneN7sCl/bVsbhxh+5jmITxbMUlRJmyg9oLGL+w9ai2+pPupWW6eFfCTbEM/U+XzbhtPC0oBkwKMfx5T9IWTbrMpPuVU4RvI3QhRCERHlZvLrrJwE4MouQO8xQcD1l/yw5vZjYDAUlprc0zJJqkKVZpnjnb5nVx6MfUjJkpSXuafqcBi5ZeHOX3tCOjdhjRiVmbARncjgs=
