version: '3'
services:
  hacker_cookbook:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: hacker_cookbook
    ports:
      - "5000:5000"
    volumes:
      - .:/app
