name: markdown
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v3.2.0
      with:
        files: .
        config_file: ".markdownlint.json"